# Generated by Django 4.0.4 on 2022-05-02 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LearningModules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_title', models.CharField(max_length=500)),
                ('module_summary', models.CharField(max_length=1000)),
                ('module_text', models.CharField(max_length=1000000)),
                ('module_action_link', models.URLField(max_length=1000)),
            ],
        ),
    ]
