# Generated by Django 4.0.4 on 2022-05-02 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('occ', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningmodules',
            name='module_points',
            field=models.IntegerField(default=0),
        ),
    ]
