# Generated by Django 4.0.4 on 2022-05-02 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('occ', '0002_learningmodules_module_points'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learningmodules',
            name='id',
        ),
        migrations.AddField(
            model_name='learningmodules',
            name='module_id',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
