# Generated by Django 4.0.4 on 2022-05-02 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('occ', '0004_userpoints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpoints',
            name='username',
            field=models.CharField(max_length=1000),
        ),
    ]
