# Generated by Django 4.0.4 on 2022-05-02 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('occ', '0005_alter_userpoints_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompletedModules',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=1000)),
                ('points', models.IntegerField(default=0)),
                ('module_id', models.IntegerField(default=-1)),
            ],
        ),
        migrations.DeleteModel(
            name='UserPoints',
        ),
    ]
